services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ${APPDATA}/config:/config
      - ${APPDATA}/downloads:/downloads
